name: flutter_3_7_0_test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_shaders: ^0.0.6
  flex_color_scheme: ^6.1.2
  photo_view: ^0.14.0
  rive: ^0.10.1
  sensors_plus: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  shaders:
    - shaders/dir_glow.glsl
  assets:
    - assets/
